/**
 * Copyright FunASR (https://github.com/alibaba-damo-academy/FunASR). All Rights
 * Reserved. MIT License  (https://opensource.org/licenses/MIT)
 */
/* 2022-2023 by zhaoming,mali aihealthx.com */

!function(a,b){"use strict";a.RecorderLM="2022.05.16",a.Recorder=function(c){return new e(c)};var c={Hash:{},canProcess:function(a,b){var c=this.Hash[a];return c&&c.stable&&(!b||c[b])},load:function(a,b){var c=this,d=c.Hash[a];return d||(d=c.Hash[a]={stable:!1,id:a}),d.call=function(){return b(d,c.Hash),d},d.call()}};a.Recorder.Destroy=function(){for(var c in a.Recorder)a.Recorder.hasOwnProperty(c)&&"Destroy"!=c&&delete a.Recorder[c];b.RecorderLM&&delete b.RecorderLM,c=0};var d=b.URL||b.webkitURL,e=function(c){var d=this;if(c=c||{},d.set=function(a){a=a||{};var b={type:"mp3",bitRate:16,sampleRate:16e3,bufferSize:8192,onProcess:function(a,b,c,d,e,f){},takeoffEncodeChunk:function(a,b,c,d,e,f,g){},fileSize:0,frameType:[]};for(var c in b)a[c]===undefined&&(a[c]=b[c]);for(var c in a)d[c]=a[c]};var e=/^audio/,f=c.type;f&&!e.test(f)&&(c.type="audio/"+f),/webm/.test(f)&&!c.bitRate&&(c.bitRate=128),d.set(c),d.buffers=[],d.srcSampleRate=0,d.state="null",d.envStart=0,d.envInLast=0,d._S=9};"object"==typeof navigator&&"MediaRecorder"in b&&"mic"==b.RecorderLM&&(b.RecorderLM="app");var f=e.prototype;f.open=function(a,c){a=a||function(){},c=c||function(a){console.error(a)};var d=this;if("null"!=d.state)return c("未处于null状态");if(b.AudioContext=b.AudioContext||b.webkitAudioContext,!b.AudioContext)return c("不支持AudioContext");var e=function(){var b=navigator.mediaDevices||{};if(!b.getUserMedia){b=navigator;var e=b.getUserMedia||b.webkitGetUserMedia||b.mozGetUserMedia||b.msGetUserMedia;if(!e)return c("无法录音：未找到getUserMedia");b.getUserMedia=function(a,b,c){e.call(navigator,a,b,c)}}var f={audio:!0};b.getUserMedia(f,function(b){d.streamContext=b,d.api=new b.AudioContext,
d.srcSampleRate=d.api.sampleRate;var e=d.api.createMediaStreamSource(b);d.mediaProcess=d.api.createScriptProcessor||d.api.createJavaScriptNode,d.mediaProcess=d.mediaProcess.call(d.api,d.bufferSize,1,1);var f;try{d.media=e,d.media.connect(d.mediaProcess),d.mediaProcess.connect(d.api.destination);var g=d.stream=d.api.createGain();e.connect(g),g.connect(d.api.destination),d.state="ready",a()}catch(e){f=e}f&&(d.state="null",c(f))},function(a){c(a)})};e()},f.close=function(a){a=a||function(){};var c=this;if("null"!=c.state){"ready"==c.state&&c.mediaProcess&&(c.mediaProcess.disconnect(),c.media&&c.media.disconnect(),c.mediaProcess=null,c.media=null);try{c.streamContext.getTracks&&c.streamContext.getTracks().forEach(function(a){a.stop()}),"function"==typeof c.streamContext.stop&&c.streamContext.stop()}catch(a){}c.streamContext=null,c.stream&&(c.stream.disconnect(),c.stream=null),c.api&&("function"==typeof c.api.close&&c.api.close(),c.api=null),c.buffer=[],c.state="null",c.buffers=[],
c.srcSampleRate=0,a()}},f.start=function(){var a=this;if("ready"==a.state){a.state="recording";var c=a.mediaProcess,d=a.media;a.envStart=Date.now(),a.envInLast=a.envStart,a.buffers=[],c.onaudioprocess=function(e){if("recording"==a.state){var f=e.inputBuffer.getChannelData(0);a.buffers.push(new Float32Array(f));var g=Date.now(),h=g-a.envStart,i=g-a.envInLast;a.envInLast=g;var j=a.buffers.length;a.onProcess(f,h,i,j,b.
URL.createObjectURL(new Blob([encodeWAV(f,a.srcSampleRate,a.sampleRate)], {type: 'audio/wav'})),c.onaudioprocess)}}}}else console.error("未open")};var

encodeWAV=function(a,b,c){function d(a){for(var b=new Uint8Array(a.length),c=0;c<b.length;c++){var d=a[c];b[c]=d}return b}var e=new Int16Array(a.length);for(var f in a)e[f]=32767*Math.min(1,a[f]);var g=e.buffer,h=new DataView(g);b=b||8e3,c=c||8e3;var i=c/b;if(i!=1){e=m(e,i),h=new DataView(e.buffer)}var s=e.length*2,t=new ArrayBuffer(44+s),j=new DataView(t),k=function(a,b,c){for(var d=0;d<c.length;d++)a.setUint8(b+d,c.charCodeAt(d))};return k(j,0,"RIFF"),j.setUint32(4,36+s,!0),k(j,8,"WAVE"),k(j,12,"fmt "),j.setUint32(16,16,!0),j.setUint16(20,1,!0),j.setUint16(22,1,!0),j.setUint32(24,c,!0),j.setUint32(28,2*c,!0),j.setUint16(32,2,!0),j.setUint16(34,16,!0),k(j,36,"data"),j.setUint32(40,s,!0),d(new Uint8Array(j.buffer))}

f.pause=function(){var a=this;a.state="paused"};var g=function(a,b){for(var c=[],d=0,e=a.length;d<e;)c.push(a.slice(d,d+=b));return c};f.resume=function(){var a=this;"paused"==a.state&&(a.state="recording")},f.stop=function(a,e){var f=this;a=a||function(){},e=e||function(){};var g=
function(){for(var b=new Float32Array(0),g=0,i=f.buffers.length;g<i;g++){var j=f.buffers[g],k=b.length;b=h(b,j.length+k),b.set(j,k)}var l=encodeWAV(b,f.srcSampleRate,f.sampleRate),m=new Blob([l],{type:"audio/wav"}),n=b.length,o=Math.floor(n/(f.srcSampleRate/1e3));a(m,o)};if(f.state!="recording"){f.state="stop",f.close();return}f.state="stop";var h=function(a,b){var c=new Float32Array(b);return c.set(a,0),c};g()};var h=function(a,b){var c=new Float32Array(b);return c.set(a,0),c};var m=function(a,b){return Recorder.SampleData?Recorder.SampleData(a,b,!0).data:new Int16Array(Math.floor(a.length/b))},n=function(a,b,c){var d=a[0],e=a.length;if(e!=1)for(var f=b,g=0;f<c;)g=(f-b)/(c-b),a[f]=d+(a[e-1]-d)*g,f++};a.Recorder[f._S]=f;

a.Recorder.SampleData=function(a,b,c,d){var e=a.length,f=Math.floor(e/b),g=f,h=0,i=new Int16Array(g),j=b,k=0;for(var l=0;l<g;l++){var m=Math.floor(l*j),n=0,o=0;for(;o<j&&m+o<e;o++){var p=a[m+o];n+=p}i[l]=n/j*d||0,n>h&&(h=n,k=l)}if(!c)return{index:k,level:h,data:i};c=c===!0?0.5:c;var g=Math.floor(f/b*c);g<1&&(g=1);var i2=new Int16Array(g),j=f/g;for(var l=0;l<g;l++){var m=Math.floor(l*j),n=0,o=0;for(;o<j&&m+o<f;o++){var p=i[m+o];n+=p}i2[l]=n/j||0}return{index:Math.floor(k/f*g),level:h,data:i2}}}(this,window);